name: Tama-Gargoyle Bug
description: Template for reporting bugs
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      options:
        - MVP
        - 19th of December Reports
        - 5th of January Reports
        - 6th of January Reports
        - 7th of January Reports
        - 8th of January Reports
        - 9th of January Reports
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - "Critical"
        - "High"
        - "Medium"
        - "Low"
        - "Trivial"
  - type: dropdown
    id: suggested_priority
    attributes:
      label: Suggested Priority
      description: To aid decision of review urgency
      options:
        - High
        - Medium
        - Low
  - type: textarea
    id: observed
    attributes:
      label: Observed Behaviour
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      value: |
        1.
        2.
        3.